worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;

    upstream frontend { server frontend:3000; }
    upstream api { server api:5000; }
    upstream grafana { server grafana:3000; }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://frontend;
        }

        location /api/ {
            proxy_pass http://api/;
        }

        location /grafana/ {
            proxy_pass http://grafana/;
        }
    }
}
