import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';

export function writeNginxAppConfig(slug: string, port: number): void {
  const nginxAppsDir = path.join(process.env.PROJECT_PATH || '/workspace', 'nginx-apps', 'paths');
  fs.mkdirSync(nginxAppsDir, { recursive: true });

  const confContent = `# Auto-generated by VulcanPaaS for app: ${slug}\nlocation /apps/${slug}/ {\n    proxy_pass http://host-gateway:${port}/;\n    proxy_set_header Host $host;\n    proxy_set_header X-Real-IP $remote_addr;\n    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n    proxy_http_version 1.1;\n    proxy_set_header Upgrade $http_upgrade;\n    proxy_set_header Connection "upgrade";\n}\n`;
  fs.writeFileSync(path.join(nginxAppsDir, `${slug}.conf`), confContent, 'utf8');
  console.info(`Wrote nginx path config for ${slug} → port ${port}`);
}

export function isDomainAllowed(domain: string): boolean {
  const whitelist = process.env.ALLOWED_DOMAINS;
  if (!whitelist || whitelist.trim() === '') {
    console.warn(`ALLOWED_DOMAINS not set — allowing domain: ${domain}`);
    return true;
  }
  const allowed = whitelist.split(',').map(d => d.trim().toLowerCase());
  const isAllowed = allowed.includes(domain.trim().toLowerCase());
  if (!isAllowed) {
    console.error(`Domain "${domain}" is NOT in ALLOWED_DOMAINS — rejecting.`);
  }
  return isAllowed;
}

export function writeDomainNginxConfig(domain: string, port: number): void {
  const nginxAppsDir = path.join(process.env.PROJECT_PATH || '/workspace', 'nginx-apps', 'domains');
  fs.mkdirSync(nginxAppsDir, { recursive: true });
  const safeSlug = domain.replace(/[^a-zA-Z0-9.-]/g, '_');

  const confContent = `# Auto-generated by VulcanPaaS for custom domain: ${domain}\nserver {\n    listen 80;\n    server_name ${domain} www.${domain};\n\n    location / {\n        proxy_pass http://host-gateway:${port}/;\n        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_http_version 1.1;\n        proxy_set_header Upgrade $http_upgrade;\n        proxy_set_header Connection "upgrade";\n    }\n}\n`;
  fs.writeFileSync(path.join(nginxAppsDir, `${safeSlug}.conf`), confContent, 'utf8');
  console.info(`Wrote domain nginx server block: ${domain} → port ${port}`);
}

export function reloadNginx(): void {
  exec('docker exec vulcanpaas-nginx nginx -s reload', (err, stdout, stderr) => {
    if (err) {
      console.error(`nginx reload failed: ${stderr}`);
    } else {
      console.info('nginx reloaded successfully');
    }
  });
}
